import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';
import Image from 'next/image';

const dietPlan = {
    'Day 1': {
        Breakfast: { meal: 'Oatmeal with berries and nuts', image: 'https://placehold.co/300x200.png', hint: 'oatmeal berries' },
        Lunch: { meal: 'Grilled chicken salad with vinaigrette', image: 'https://placehold.co/300x200.png', hint: 'chicken salad' },
        Dinner: { meal: 'Salmon with roasted vegetables', image: 'https://placehold.co/300x200.png', hint: 'salmon vegetables' },
    },
    'Day 2': {
        Breakfast: { meal: 'Greek yogurt with honey and fruits', image: 'https://placehold.co/300x200.png', hint: 'yogurt fruit' },
        Lunch: { meal: 'Quinoa bowl with black beans and corn', image: 'https://placehold.co/300x200.png', hint: 'quinoa bowl' },
        Dinner: { meal: 'Lean beef stir-fry with brown rice', image: 'https://placehold.co/300x200.png', hint: 'beef stir-fry' },
    },
    'Day 3': {
        Breakfast: { meal: 'Scrambled eggs with spinach and whole-wheat toast', image: 'https://placehold.co/300x200.png', hint: 'scrambled eggs' },
        Lunch: { meal: 'Lentil soup with a side of mixed greens', image: 'https://placehold.co/300x200.png', hint: 'lentil soup' },
        Dinner: { meal: 'Baked cod with asparagus and lemon', image: 'https://placehold.co/300x200.png', hint: 'baked cod' },
    },
    'Day 4': {
        Breakfast: { meal: 'Smoothie with spinach, banana, and protein powder', image: 'https://placehold.co/300x200.png', hint: 'green smoothie' },
        Lunch: { meal: 'Turkey and avocado wrap on whole-wheat tortilla', image: 'https://placehold.co/300x200.png', hint: 'turkey wrap' },
        Dinner: { meal: 'Chicken cacciatore with whole-wheat pasta', image: 'https://placehold.co/300x200.png', hint: 'chicken pasta' },
    },
    'Day 5': {
        Breakfast: { meal: 'Oatmeal with berries and nuts', image: 'https://placehold.co/300x200.png', hint: 'oatmeal berries' },
        Lunch: { meal: 'Grilled chicken salad with vinaigrette', image: 'https://placehold.co/300x200.png', hint: 'chicken salad' },
        Dinner: { meal: 'Salmon with roasted vegetables', image: 'https://placehold.co/300x200.png', hint: 'salmon vegetables' },
    },
    'Day 6': {
        Breakfast: { meal: 'Greek yogurt with honey and fruits', image: 'https://placehold.co/300x200.png', hint: 'yogurt fruit' },
        Lunch: { meal: 'Quinoa bowl with black beans and corn', image: 'https://placehold.co/300x200.png', hint: 'quinoa bowl' },
        Dinner: { meal: 'Lean beef stir-fry with brown rice', image: 'https://placehold.co/300x200.png', hint: 'beef stir-fry' },
    },
    'Day 7': {
        Breakfast: { meal: 'Scrambled eggs with spinach and whole-wheat toast', image: 'https://placehold.co/300x200.png', hint: 'scrambled eggs' },
        Lunch: { meal: 'Lentil soup with a side of mixed greens', image: 'https://placehold.co/300x200.png', hint: 'lentil soup' },
        Dinner: { meal: 'Baked cod with asparagus and lemon', image: 'https://placehold.co/300x200.png', hint: 'baked cod' },
    },
};

type Meal = {
    meal: string;
    image: string;
    hint: string;
};

type DayPlan = {
    Breakfast: Meal;
    Lunch: Meal;
    Dinner: Meal;
};

export default function DietPlanPage() {
    return (
        <div className="space-y-6">
            <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                <div>
                    <h2 className="text-3xl font-bold tracking-tight font-headline">Your 7-Day Diet Plan</h2>
                    <p className="text-muted-foreground">Generated by Aziaf AI to help you reach your goals.</p>
                </div>
                <Button>
                    <Download className="mr-2 h-4 w-4" />
                    Download Plan
                </Button>
            </div>
            
            <Tabs defaultValue="Day 1" className="w-full">
                <TabsList className="grid w-full grid-cols-3 sm:grid-cols-4 md:grid-cols-7">
                    {Object.keys(dietPlan).map((day) => (
                        <TabsTrigger key={day} value={day}>{day.replace(' ', '\n')}</TabsTrigger>
                    ))}
                </TabsList>
                {Object.entries(dietPlan).map(([day, meals]) => (
                    <TabsContent key={day} value={day}>
                        <div className="grid gap-6 mt-4 md:grid-cols-2 lg:grid-cols-3">
                            {Object.entries(meals as DayPlan).map(([mealTime, mealDetails]) => (
                                <Card key={mealTime} className="overflow-hidden">
                                    <CardHeader className="p-0">
                                        <Image
                                            src={mealDetails.image}
                                            alt={mealDetails.meal}
                                            width={300}
                                            height={200}
                                            className="rounded-t-lg object-cover w-full aspect-[3/2]"
                                            data-ai-hint={mealDetails.hint}
                                        />
                                    </CardHeader>
                                    <CardContent className="p-4">
                                        <h3 className="text-lg font-semibold font-headline">{mealTime}</h3>
                                        <p className="text-muted-foreground">{mealDetails.meal}</p>
                                    </CardContent>
                                </Card>
                            ))}
                        </div>
                    </TabsContent>
                ))}
            </Tabs>
        </div>
    );
}
